//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MFrameWork_LoadResPriorityWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(MFrameWork.LoadResPriority));
		L.RegVar("RES_LOAD_LEVEL_HEIGHT", get_RES_LOAD_LEVEL_HEIGHT, null);
		L.RegVar("RES_LOAD_LEVEL_MEDIAL", get_RES_LOAD_LEVEL_MEDIAL, null);
		L.RegVar("RES_LOAD_LEVEL_NORMAL", get_RES_LOAD_LEVEL_NORMAL, null);
		L.RegVar("RES_LOAD_LEVEL_LOW", get_RES_LOAD_LEVEL_LOW, null);
		L.RegVar("RES_LOAD_LEVEL_COUNT", get_RES_LOAD_LEVEL_COUNT, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<MFrameWork.LoadResPriority>.Check = CheckType;
		StackTraits<MFrameWork.LoadResPriority>.Push = Push;
	}

	static void Push(IntPtr L, MFrameWork.LoadResPriority arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(MFrameWork.LoadResPriority), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RES_LOAD_LEVEL_HEIGHT(IntPtr L)
	{
		ToLua.Push(L, MFrameWork.LoadResPriority.RES_LOAD_LEVEL_HEIGHT);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RES_LOAD_LEVEL_MEDIAL(IntPtr L)
	{
		ToLua.Push(L, MFrameWork.LoadResPriority.RES_LOAD_LEVEL_MEDIAL);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RES_LOAD_LEVEL_NORMAL(IntPtr L)
	{
		ToLua.Push(L, MFrameWork.LoadResPriority.RES_LOAD_LEVEL_NORMAL);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RES_LOAD_LEVEL_LOW(IntPtr L)
	{
		ToLua.Push(L, MFrameWork.LoadResPriority.RES_LOAD_LEVEL_LOW);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RES_LOAD_LEVEL_COUNT(IntPtr L)
	{
		ToLua.Push(L, MFrameWork.LoadResPriority.RES_LOAD_LEVEL_COUNT);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		MFrameWork.LoadResPriority o = (MFrameWork.LoadResPriority)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

